# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths: 
      - Source/frontend/**
      - .github/**
  pull_request:
    branches: [ "main" ]
    paths: 
      - Source/frontend/**
      - .github/**

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Source/frontend

    strategy:
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: Source/frontend/package-lock.json
    - run: npm ci
      working-directory: ./Source/frontend
    - run: npm run build --if-present
      working-directory: ./Source/frontend
    - run: npm test
      working-directory: ./Source/frontend
